### ISSUE TITLE
启动报错AdapterTypeUnknown

### ISSUE THREAD

**Issue by Tony2055866** [zhuhaow/Specht#1]
帮忙看个问题，使用你推荐的模版，启动时报错
Error when loading config file: /xxxxxxx/.Specht/Conf.yaml. AdapterTypeUnknown
多谢！

https://github.com/HoonHwang/SpechtLiteConf

**Comment by Tony2055866** [comment]
直接复制https://github.com/zhuhaow/SpechtLite 这上面的demo    又报InvalidYamlFile错误

**Comment by zhuhaow** [comment]
要么把NEKit版本升级一下要么把reject adapter去掉试试

Best regards,
Zhuhao Wang

2016年9月30日 +0800 17:34 gaotong2055 notifications@github.com，写道：

**Comment by Tony2055866** [comment]
升级之后解决了，多谢啦
