### ISSUE TITLE
Prebuilt binary?

### ISSUE THREAD

**Issue by netheril96** [zhuhaow/Specht#3]
According to the latest https://developer.apple.com/reference/networkextension,

> Network Extension Entitlement
> Except when you use the NEHotspotHelper class, you do not need to obtain entitlements from Apple to use Network Extension classes. To request an entitlement to use the NEHotspotHelper class, visit https://developer.apple.com/contact/network-extension.

So if my understanding is not wrong, Apple has changed the policy such that entitlements are not necessary anymore. Could you build a binary distribution?

**Comment by zhuhaow** [comment]
Apple does not require you to apply for the entitlement anymore does not mean it permits you to distribute app with NE entitlement outside App Store. 
Last time I checked  it was forbidden, you may check it again.
