### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by Ricardo1980** [zhuhaow/Specht#7]
I guess this:
"The core of Specht consists just a few lines of code invoking NEKit. Specht is mainly provided as a demo for developers who want to work with NEKit. Use SpechtLite if you are not interested in NEKit."
Should be:
"The core of Specht consists just a few lines of code invoking NEKit. Specht is mainly provided as a demo for developers who want to work with NEKit. Use SpechtLite if you are not interested in NetworkExtension."

**Comment by zhuhaow** [comment]
Corrected. Thank you.
